config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :quotes

  root 'quotes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.all.order('created_at DESC')
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(post_params)
    if @quote.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def show
    @quote = Quote.find(params[:id])
  end

private
  
  def post_params
    params.require(:quote).permit(:content, :author)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quotesite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/index.html.erb
<section class="hero is-info is-large">
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to 'Quotes', root_path, class: 'navbar-item' %> 
          <span class="navbar-burger burger" data-target="navbarMenuHeroB">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroB" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
              <%= button_to "Add New Quote", new_quote_path, :method => "get",class: 'button is-info is-inverted' %>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <div class="hero-body">
    <div class="container has-text-centered">
      <% @quotes.each do |quote| %>
        <div class="">
            <div class="card-content">
            <h1 class="title">
                <%= quote.content  %>
            </h1>
            <h2 class="subtitle">
                <%= quote.author %>
            </h2>

            </div>
        </div>
        <% end %>
    </div>
  </div>

  
</section>


app/views/quotes/new.html.erb
<section class="hero is-info is-large">
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to 'Quotes', root_path, class: 'navbar-item' %> 
          <span class="navbar-burger burger" data-target="navbarMenuHeroB">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroB" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
              <%= button_to "Add New Quote", new_quote_path, :method => "get",class: 'button is-info is-inverted' %>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <div class="hero-body">
    <div class="container">
    <%= simple_form_for @quote do |f| %>
        <div class="field">
            <div class="control">
            <%= f.input :content, input_html: {class: 'textarea'}, wrapper: false, label_html: { class: 'label'} %>
            </div>
        </div>
         <div class="field">
            <div class="control">
            <%= f.input :author, input_html: {class: 'input'}, wrapper: false, label_html: { class: 'label'} %>
            </div>
        </div>
        <%= f.button :submit, 'Create new Quote', class: "button is-primary" %>
    <% end %>    
    </div>
  </div>

  
</section>

app/views/quotes/show.html.erb

<section class="hero is-medium is-primary is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
         <%= @quote.content %>
      </h1>
      <h2 class="subtitle">
        <%= @quote.author %>
      </h2>
    </div>
  </div>
</section>